### ISSUE TITLE
Space complexity reduction

### ISSUE THREAD

**Issue by rahulsrma26** [yashkumar1122/ol_codes#1]
@yashkumar1122 the following code can be done with O(1) space complexity instead of O(n).
https://github.com/yashkumar1122/ol_codes/blob/642329ea18e0be0b5e9a98f1e655546818c128e6/JTS/CF-A/CF677-D2-A/Main.java#L15

**Comment by yashkumar1122** [comment]
[Fixed](https://github.com/yashkumar1122/ol_codes/commit/0619c4de32decb5e93078f1ec6a35d2e7e4ccc0f)
